
# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name:        "Sarah M Brown"
keywords:    "machine learning, research, stem diversity"
# email: you@example.com
description: Sarah M Brown, PhD ML Researcher, STEM diversity leader
footer_text: Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url: "https://github.com/sarahmbrown-org/sarahmbrown-org.github.io" # the base hostname & protocol for your site
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: brownsarahm
twitter_username: brownsarahm
linkedin_username: smariebrown
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
contact_note: >
  You can even add a little note about which of these is the best way to reach you.

google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: ...
blog_description: thoughts as a junior academic

# Pagination
paginate: 10
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    menuloc: news
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  bio:
  academic:
    output: true
    menuloc: about
    permalink: /:name/
  research:
    output: true
    display: research
    menuloc: research
    permalink: /:collection/:title
  service:
    output: true
    display: service
    menuloc: service
    permalink: /:collection/:title
  speaking:
    output: true
    display: speaking
    menuloc: speaking
    permalink: /:collection/:title
  teaching:
    output: true
    display: teaching
    menuloc: teaching
    permalink: /:collection/:year/:title
  blog:
    output: true
    permalink: /:collection/:namp
    display: blog
    menuloc: blog
  category:
    output: true
    permalink: /:collection/:name/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    # - jekyll-email-protect
    - jekyll-paginate
    # - jekyll/scholar
    # - jemoji

# Jekyll-Scholar
scholar:

  last_name: Brown

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"

### template colors, used site-wide via css ###
colors:
  black: '#2A312E'
  white: '#FBFBFB'
#  white:     '#D9E2E5'
  gray:      '#2A312E'
  magenta:   '#92374D'
  purple: '#462138'
  blue: '#8EB1C7'
  teal: '#465B64'
  # unused

  green:     '#9bcf2f'
##  purple:    '#c869bf'
  orange:    '#fab125'

include:
  - _pages
  - files
